#!/bin/bash

# List of Pokémon
POKEMONS=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")

# Fetch function
fetch_pokemon() {
    name=$1
    curl -s "https://pokeapi.co/api/v2/pokemon/${name,,}" \
        | jq '.name, .id, .types[].type.name'
}

# Start background jobs
for pokemon in "${POKEMONS[@]}"; do
    fetch_pokemon "$pokemon" &
done

# Show running jobs
jobs

# Wait for all jobs to finish
wait

# (Optional) Kill any stray jobs (in case something hangs)
jobs -p | xargs kill 2>/dev/null
