#!/bin/bash

JSON_FILE="data.json"

NAME=$(jq -r '.name' "$JSON_FILE" | sed 's/.*/\u&/')  # Capitalize first letter
HEIGHT=$(jq '.height' "$JSON_FILE")
WEIGHT=$(jq '.weight' "$JSON_FILE")
TYPE=$(jq -r '.types[0].type.name' "$JSON_FILE" | sed 's/.*/\u&/')

# Convert decimetres to metres, hectograms to kg
HEIGHT_M=$(awk -v h="$HEIGHT" 'BEGIN {print h/10}')
WEIGHT_KG=$(awk -v w="$WEIGHT" 'BEGIN {print w/10}')

echo "$NAME is of type $TYPE, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_M}m tall."
