#!/bin/bash
# Extracts Pikachu stats from data.json

NAME=$(jq -r '.name' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
WEIGHT=$(jq -r '.weight/10' data.json)  # Convert from hectograms to kg
HEIGHT=$(jq -r '.height/10' data.json)  # Convert from decimeters to meters

echo "${NAME} is of type ${TYPE}, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."